insert into book (id_book, title, description, autor) values (1, 'Ninja III: The Domination', 'Burn of unspecified degree of left scapular region', 'Ashia Hardcastle');
insert into book (id_book, title, description, autor) values (2, 'Shanghai Knights', 'Secondary malignant neoplasm of right adrenal gland', 'Eugene Quidenham');
insert into book (id_book, title, description, autor) values (3, 'Funny Bones', 'Psoriasis', 'Michael MacGillicuddy');
insert into book (id_book, title, description, autor) values (4, 'Fish Tank', 'Driver of 3-whl mv injured in clsn w statnry object nontraf', 'Claudelle Chmiel');
insert into book (id_book, title, description, autor) values (5, 'Sweet Mud (Adama Meshuga''at)', 'Traumatic compartment syndrome of left lower extremity', 'Anestassia Giberd');
insert into book (id_book, title, description, autor) values (6, 'Stranger, The', 'Unstbl burst fx second lum vert, subs for fx w routn heal', 'Lizette Duinbleton');
insert into book (id_book, title, description, autor) values (7, 'PTU', 'Contusion of fallopian tube, unspecified, sequela', 'Lizzy Perry');
insert into book (id_book, title, description, autor) values (8, 'Escuela de seducción', 'Displ commnt fx shaft of ulna, l arm, 7thG', 'Skell Boskell');
insert into book (id_book, title, description, autor) values (9, 'Missile to the Moon', 'Open bite, right thigh, sequela', 'Faustina Nizard');
insert into book (id_book, title, description, autor) values (10, 'Unforgotten: Twenty-Five Years After Willowbrook', 'Unsp injury of musc/fasc/tend at wrs/hnd lv, left hand, subs', 'Base Brydon');
insert into book (id_book, title, description, autor) values (11, 'Bronson', 'Allergy, unspecified, subsequent encounter', 'Christoffer Ghioni');
insert into book (id_book, title, description, autor) values (12, 'Suture', 'Allergy, unspecified', 'Noell Beau');
insert into book (id_book, title, description, autor) values (13, 'Tetsuo III: The Bullet Man', 'Idiopathic gout, ankle and foot', 'Tawnya Sells');
insert into book (id_book, title, description, autor) values (14, 'Sylvia Scarlett', 'Other superficial bite of right thigh, subsequent encounter', 'Dannel Janton');
insert into book (id_book, title, description, autor) values (15, 'Investigating Sex (a.k.a. Intimate Affairs)', 'Osteonecrosis in diseases classified elsewhere, lower leg', 'Anica Mingo');
insert into book (id_book, title, description, autor) values (16, 'Jingle All the Way 2', 'Tuberculosis of thyroid gland', 'Amber Mulloch');
insert into book (id_book, title, description, autor) values (17, 'Inbetween Worlds', 'Displ commnt fx shaft of unsp femr, 7thE', 'Hamil Griffiths');
insert into book (id_book, title, description, autor) values (18, 'Expired', 'Malig neoplasm of scapula and long bones of unsp upper limb', 'Sarene Deacon');
insert into book (id_book, title, description, autor) values (19, 'Thirteen Women', 'Subluxation of distal interphalangeal joint of thmb, sequela', 'Free Weighell');
insert into book (id_book, title, description, autor) values (20, 'Chop Shop', 'Inferior dislocation of unspecified humerus, subs encntr', 'Melisenda Lissett');
insert into book (id_book, title, description, autor) values (21, 'Ricky & Barabba', 'Non-prs chr ulc unsp prt of r low leg limited to brkdwn skin', 'Arliene Tomek');
insert into book (id_book, title, description, autor) values (22, 'Bird of the Air, A (Loop, The)', 'Stress fracture, unspecified finger(s)', 'Georgina Antham');
insert into book (id_book, title, description, autor) values (23, 'Lucky Night', 'Angioneurotic edema', 'Kipp Holbarrow');
insert into book (id_book, title, description, autor) values (24, 'True Lies', 'Pnctr w fb of right thumb w damage to nail, sequela', 'Devlin Margeram');
insert into book (id_book, title, description, autor) values (25, 'Gold Diggers of 1935', 'Unsp injury of other blood vessels at wrist and hand level', 'Maible Curman');
insert into book (id_book, title, description, autor) values (26, 'Notebook, The', 'Fall on board fishing boat, initial encounter', 'Henrie Yushmanov');
insert into book (id_book, title, description, autor) values (27, 'Accidental Golfer, The (Den ofrivillige golfaren)', 'Other injury of inferior vena cava, initial encounter', 'Bev O'' Hogan');
insert into book (id_book, title, description, autor) values (28, 'Damn the Defiant! (H.M.S. Defiant)', 'Unsp disp fx of 4th cervcal vert, subs for fx w delay heal', 'Gordy Leverton');
insert into book (id_book, title, description, autor) values (29, 'Crossroads', 'Disp fx of r radial styloid pro, 7thH', 'Willow Strete');
insert into book (id_book, title, description, autor) values (30, 'Nick Fury: Agent of S.H.I.E.L.D.', 'Traum rupture of ligament of r rng fngr at MCP/IP jt, init', 'Thorndike Ritelli');
insert into book (id_book, title, description, autor) values (31, 'Hot Dog... The Movie', 'Nondisp commnt fx unsp patella, 7thF', 'Annalee Grammer');
insert into book (id_book, title, description, autor) values (32, 'Spinout', 'Open bite of l frnt wl of thorax w/o penet thor cavity, subs', 'Gib Venney');
insert into book (id_book, title, description, autor) values (33, 'Who Pulled the Plug? (Göta kanal eller Vem drog ur proppen?)', 'Activity, volleyball (beach) (court)', 'Maud Duckwith');
insert into book (id_book, title, description, autor) values (34, 'Stranger than Fiction', 'Other yatapoxvirus infections', 'Rice de Clerq');
insert into book (id_book, title, description, autor) values (35, 'Tie That Binds, The', 'Fall from other furniture, sequela', 'Masha MacCallion');
insert into book (id_book, title, description, autor) values (36, 'Kedma', 'Acute lymphangitis of left finger', 'Hugo Proud');
insert into book (id_book, title, description, autor) values (37, 'Willie & Phil', 'Colles'' fx unsp rad, subs for opn fx type I/2 w delay heal', 'Lissy Antognelli');
insert into book (id_book, title, description, autor) values (38, 'I Do', 'Nondisp fx of trapezm, unsp wrist, subs for fx w delay heal', 'Derrick Higgen');
insert into book (id_book, title, description, autor) values (39, 'Julia and Julia (Giulia e Giulia)', 'Nondisp intartic fx l calcaneus, subs for fx w routn heal', 'Sharia Arens');
insert into book (id_book, title, description, autor) values (40, 'Adam Resurrected', 'Maternal care for congenital malformation of uterus', 'Konstanze Roantree');
insert into book (id_book, title, description, autor) values (41, 'Playing from the Plate (Grajacy z talerza)', 'Corrosion of first degree of unsp lower leg, subs encntr', 'Marlene Mosey');
insert into book (id_book, title, description, autor) values (42, 'Citizen Ruth', 'Laceration without foreign body, right hip', 'Peadar Quirke');
insert into book (id_book, title, description, autor) values (43, 'Decline of the American Empire, The (Déclin de l''empire américain, Le)', 'Toxic effect of paints and dyes, NEC, self-harm, subs', 'Cynthea Pentercost');
insert into book (id_book, title, description, autor) values (44, 'Kiss Me Goodbye', 'Nondisp bimalleol fx r low leg, subs for clos fx w malunion', 'Miguelita Cortnay');
insert into book (id_book, title, description, autor) values (45, 'Flypaper', 'Milt op involving unsp weapon of mass destruction, init', 'Bret Loude');
insert into book (id_book, title, description, autor) values (46, 'My Name Is Bruce', 'Contact with other and unspecified machinery', 'Dreddy Sheringham');
insert into book (id_book, title, description, autor) values (47, 'The Big Shave', 'Burn 1st deg mult sites of left lower limb, ex ank/ft, init', 'Antonin Chadburn');
insert into book (id_book, title, description, autor) values (48, 'Love and Anarchy (Film d''amore e d''anarchia, ovvero ''stamattina alle 10 in via dei Fiori nella nota casa di tolleranza...'')', 'Unspecified viral hepatitis B without hepatic coma', 'Kristina Bourtoumieux');
insert into book (id_book, title, description, autor) values (49, 'Tongan Ninja', 'Corrosion of first degree of unspecified thigh', 'Brandon Gantz');
insert into book (id_book, title, description, autor) values (50, 'Intimacy', 'Puncture wound with foreign body, right hip, sequela', 'Lennie Beton');
insert into book (id_book, title, description, autor) values (51, 'Prince & Me II: The Royal Wedding, The', 'Acquired absence of right ankle', 'Boyce Stedson');
insert into book (id_book, title, description, autor) values (52, 'Ex-Girlfriends', 'Unsp superficial injuries of breast, right breast, subs', 'Shir De Souza');
insert into book (id_book, title, description, autor) values (53, 'Li''l Abner', 'Displ spiral fx shaft of unsp tibia, 7thK', 'Claudie Corinton');
insert into book (id_book, title, description, autor) values (54, 'North Country', 'Other foreign object in esophagus causing other injury', 'Fairlie Torres');
insert into book (id_book, title, description, autor) values (55, 'Pinocchio and the Emperor of the Night', 'Corrosion of internal genitourinary organs', 'Jen Kynder');
insert into book (id_book, title, description, autor) values (56, 'Unknown White Male', 'Acute mastoiditis without complications', 'Jackie Waghorn');
insert into book (id_book, title, description, autor) values (57, 'Q: The Winged Serpent', 'Myositis ossificans progressiva, unspecified toe(s)', 'Marlee Calafate');
insert into book (id_book, title, description, autor) values (58, 'Quartier Mozart', 'Passenger of amblnc/fire eng injured in traf, sequela', 'Paula Selburn');
insert into book (id_book, title, description, autor) values (59, 'Vicky Donor', 'Food in larynx', 'Aurore Labroue');
insert into book (id_book, title, description, autor) values (60, 'But Forever in My Mind', 'Contusion of right thumb without damage to nail, init encntr', 'Michaella Smurfit');
insert into book (id_book, title, description, autor) values (61, 'Général Idi Amin Dada: A Self Portrait (Général Idi Amin Dada: Autoportrait)', 'Nondisp fx of neck of fifth MC bone, right hand, sequela', 'Korie Carbry');
insert into book (id_book, title, description, autor) values (62, 'Second Time Around, The', 'Frostbite with tissue necrosis of unsp arm, init encntr', 'Cleon MacRorie');
insert into book (id_book, title, description, autor) values (63, 'Belle comme la femme d''un autre', 'Adhesions and ankylosis of temporomandibular joint', 'Emlyn Harbert');
insert into book (id_book, title, description, autor) values (64, 'The Last Farm', 'Fall same lev from slip/trip w strike agnst unsp sharp obj', 'Carole Bernat');
insert into book (id_book, title, description, autor) values (65, 'Billy the Kid vs. Dracula', 'Fracture of lumbar spine and pelvis', 'Tully Loch');
insert into book (id_book, title, description, autor) values (66, 'Cutie and the Boxer', 'Displaced fracture of distal phalanx of left thumb', 'Thatch Murrhardt');
insert into book (id_book, title, description, autor) values (67, 'Sugar Town', 'Occup of bus injured in clsn w statnry object nontraf, subs', 'Justen Gyves');
insert into book (id_book, title, description, autor) values (68, 'The Thief', 'Occupant (driver) of hv veh injured in unsp traf, init', 'Sibbie Rushby');
insert into book (id_book, title, description, autor) values (69, 'The Gamma People', 'Corrosion of unspecified degree of left knee, init encntr', 'Ellery Aronovich');
insert into book (id_book, title, description, autor) values (70, 'Joe', 'Corros w resulting rupture and dest of left eyeball, sequela', 'Karlens Coste');
insert into book (id_book, title, description, autor) values (71, 'Starsky & Hutch', 'Other secondary osteonecrosis of radius, ulna and carpus', 'Cherin Wesson');
insert into book (id_book, title, description, autor) values (72, 'Ro.Go.Pa.G.', 'Fracture of unsp phalanx of thmb, subs for fx w nonunion', 'Kimberlyn Cavell');
insert into book (id_book, title, description, autor) values (73, 'Europa Europa (Hitlerjunge Salomon)', 'Person outside bus injured in clsn w statnry object nontraf', 'Rodi Puzey');
insert into book (id_book, title, description, autor) values (74, 'I Love Trouble', 'Enophthalmos due to trauma or surgery, right eye', 'Lorine Crathern');
insert into book (id_book, title, description, autor) values (75, 'A Gathering of Eagles', 'Unsp tear of unsp meniscus, current injury, left knee, init', 'Conny Ranken');
insert into book (id_book, title, description, autor) values (76, 'First Men in the Moon', 'Displ suprcndl fx w intrcndl extn low end r femr, 7thK', 'Joanne Dimbleby');
insert into book (id_book, title, description, autor) values (77, 'I''m a Cyborg, But That''s OK (Saibogujiman kwenchana)', 'Unspecified primary angle-closure glaucoma, severe stage', 'Fredia Readitt');
insert into book (id_book, title, description, autor) values (78, 'Victory (a.k.a. Escape to Victory)', 'Factitious disorder w predom physical signs and symptoms', 'Neda Jinkinson');
insert into book (id_book, title, description, autor) values (79, 'Rabid', 'Other physeal fracture of upper end of humerus, right arm', 'Tabbie Klaaassen');
insert into book (id_book, title, description, autor) values (80, 'On the Beach', 'Displaced fracture of medial condyle of right tibia, sequela', 'Henderson Kissack');
insert into book (id_book, title, description, autor) values (81, 'Happy Event, A (Un Heureux Evénement)', 'Transient synovitis, unspecified site', 'Ellette Chattell');
insert into book (id_book, title, description, autor) values (82, 'Karla', 'Postproc hematoma and seroma of a resp sys org fol a proc', 'Cass Keems');
insert into book (id_book, title, description, autor) values (83, 'American Psycho', 'Abrasion of breast, unspecified breast, sequela', 'Gerti Fettes');
insert into book (id_book, title, description, autor) values (84, 'Under the Skin', 'Disorder of amino-acid metabolism, unspecified', 'Rodge Rickersey');
insert into book (id_book, title, description, autor) values (85, 'Son of Paleface', 'Other forms of sporotrichosis', 'Kenn Whiteman');
insert into book (id_book, title, description, autor) values (86, 'Roller Boogie', 'Unsp superficial injury of left ring finger, subs encntr', 'Rees Leger');
insert into book (id_book, title, description, autor) values (87, 'White Rose, The (Weiße Rose, Die)', 'Thyroiditis', 'Rabbi Vahey');
insert into book (id_book, title, description, autor) values (88, 'Model', 'Disp fx of ant wall of unsp acetab, subs for fx w delay heal', 'Dollie Lambart');
insert into book (id_book, title, description, autor) values (89, 'Desert Saints', 'Displ oblique fx shaft of unsp fibula, 7thC', 'Port Dent');
insert into book (id_book, title, description, autor) values (90, 'Legend', 'Ocular hypertension, right eye', 'Blondy Stanett');
insert into book (id_book, title, description, autor) values (91, 'R-Point (Arpointeu)', 'Exposure to sofa fire due to unspecified burning material', 'Kahaleel Conor');
insert into book (id_book, title, description, autor) values (92, 'Fighting Elegy (Kenka erejii)', 'Synovial hypertrophy, not elsewhere classified, right hand', 'Shell Lambrick');
insert into book (id_book, title, description, autor) values (93, 'Wilby Wonderful', 'Unsp inflammatory spondylopathy, cervicothoracic region', 'Madlin De Filippo');
insert into book (id_book, title, description, autor) values (94, 'George Lopez: It''s Not Me, It''s You', 'Major laceration of left kidney, initial encounter', 'Lemmy Stoile');
insert into book (id_book, title, description, autor) values (95, 'No Good Deed (a.k.a. The House on Turk Street)', 'Lacerat msl/tnd lng extn msl of toe at ank/ft level, r foot', 'Kendrick Pinfold');
insert into book (id_book, title, description, autor) values (96, 'North Dallas Forty', 'Nondisp fx of medial phalanx of l idx fngr, init for opn fx', 'Celle Karpets');
insert into book (id_book, title, description, autor) values (97, 'Little Women', 'Person outsd pk-up/van inj in clsn w ped/anml in traf, sqla', 'Shawn Oloshin');
insert into book (id_book, title, description, autor) values (98, 'Notting Hill', 'Nondisp fx of lateral condyle of unspecified humerus', 'Tonie Rishbrook');
insert into book (id_book, title, description, autor) values (99, 'Critters 4', 'Unspecified subluxation of unspecified patella', 'Elinor Longbothom');
insert into book (id_book, title, description, autor) values (100, 'Scrooged', 'Chronic nephritic syndrome with other morphologic changes', 'Riki Kneeland');
